### ISSUE TITLE
REQUEST: command-line

### ISSUE THREAD

**Issue by ClaireCJS** [tranxuanthang/lrcget#151] opened 2024-10-27 05:32 UTC
Could we have it accept a filename as a command-line parameter, skip the GUI, and just perform a single download?

(I have a script to AI-transcribe my songs into LRC/SRT, but of course I don't want to do that if one already exists. So I would like to check that single song first, in an automated fashion)

**Comment by ClaireCJS** [comment] 2024-11-11 00:06
Particularly because the GUI can be unsatisfying. Right now, I'm clicking "download", and nothing is happening. There's no error message.  I'm sure if I was running it at the command line, it would give me an error message.   It says "synced" for all the lyrics, but does nothing, even though it's worked before.

**Comment by averyterrel** [comment] 2024-11-12 07:59
Duplicate of #61.

**Comment by tranxuanthang** [comment] 2024-11-12 10:07
For CLI, I believe there are currently a few tools that utilize the same LRCLIB API as LRCGET, such as https://github.com/moehmeni/syncedlyrics. I'm still interested in providing a CLI tool but this is not a very high priority. Anyways, we will track this in #61.

**Closed** 2024-11-12 10:07 UTC
Labels: duplicate
